export const dataList = [
  {
    provider: "INA d.d",
    type: "Autogas",
    fuelName: "EUROSUPER95",
    price: "0.75",
    dateCreated: "31/08/2020",
  },
  {
    provider: "INA d.d",
    type: "Autogas",
    fuelName: "EURODIESEL",
    price: "1.52",
    dateCreated: "31/08/2020",
  },
  {
    provider: "INA d.d",
    type: "Autogas",
    fuelName: "EUROSUPER95",
    price: "0.84",
    dateCreated: "31/08/2020",
  },
  {
    provider: "INA d.d",
    type: "Autogas",
    fuelName: "EUROSUPER95",
    price: "1.35",
    dateCreated: "31/08/2020",
  },
  {
    provider: "INA d.d",
    type: "Autogas",
    fuelName: "EUROSUPER95",
    price: "1.30",
    dateCreated: "31/08/2020",
  },
  {
    provider: "INA d.d",
    type: "Autogas",
    fuelName: "EUROSUPER95",
    price: "1.94",
    dateCreated: "31/08/2020",
  },
  {
    provider: "INA d.d",
    type: "Autogas",
    fuelName: "EUROSUPER95",
    price: "0.67",
    dateCreated: "31/08/2020",
  },
  {
    provider: "INA d.d",
    type: "Autogas",
    fuelName: "EUROSUPER95",
    price: "0.79",
    dateCreated: "31/08/2020",
  },
  {
    provider: "INA d.d",
    type: "Autogas",
    fuelName: "EUROSUPER95",
    price: "0.75",
    dateCreated: "31/08/2020",
  },
  {
    provider: "INA d.d",
    type: "Autogas",
    fuelName: "EUROSUPER95",
    price: "0.75",
    dateCreated: "31/08/2020",
  },
];
